# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

#https://learn.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=net%2Cbrowser

trigger:
- master

pool:
  name: Default  

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
     - script: dotnet build --configuration $(buildConfiguration)
     - script: dotnet publish -p:PublishProfile=fstools/Properties/PublishProfiles/FTPProfile.pubxml  
       displayName: 'dotnet build $(buildConfiguration)'
     - task: PublishPipelineArtifact@1
       displayName: Publish Artifact
       inputs:
         targetPath: '$(System.DefaultWorkingDirectory)/fstools/bin/Release/net8.0/publish'        
         artifactName: fstoolsWebApp

- stage: Deploy
  jobs:
  - job: DeployByFTP
    steps:
    - checkout: none
    - task: DownloadPipelineArtifact@2
      inputs:
         artifact: fstoolsWebApp
         path: $(build.artifactStagingDirectory)/website
    - task: FtpUpload@2
      inputs:
        credentialsOption: 'inputs'
        serverUrl: 'ftp://ftp.zaldo.com'
        username: $(ftpUser)
        password: $(ftpPassword)
        rootDirectory: '$(build.artifactStagingDirectory)/website'
        filePatterns: '**'
        remoteDirectory: /fstools.zaldo.com/
        clean: false
        cleanContents: false
        preservePaths: true
        trustSSL: false