# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

#https://learn.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=net%2Cbrowser

trigger:
- master


#    msdeploy -verb:sync -source:package='path/to/your/published.zip' -dest:auto,computer='server-address',site='website-name' 

pool:
  name: Default  

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
    # - script: dotnet publish -p:PublishProfile=fstools/Properties/PublishProfiles/FTPProfile.pubxml  
    #   displayName: 'dotnet build $(buildConfiguration)'

- stage: Publish
  jobs:
  - job: Publish
  steps:
  - checkout: none

  - script: echo Hello, world!
    displayName: 'Run a one-line script'  